// <auto-generated />
using System;
using HotelApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519232642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelApp.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CancellationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Requested");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            CheckInDate = new DateOnly(2026, 6, 1),
                            CheckOutDate = new DateOnly(2026, 6, 5),
                            GuestId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            RoomId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            Status = "Confirmed",
                            TotalPrice = 516.00m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            CheckInDate = new DateOnly(2026, 7, 10),
                            CheckOutDate = new DateOnly(2026, 7, 14),
                            GuestId = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            RoomId = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            Status = "Requested",
                            TotalPrice = 356.00m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            CancellationFee = 50.00m,
                            CheckInDate = new DateOnly(2026, 5, 1),
                            CheckOutDate = new DateOnly(2026, 5, 3),
                            GuestId = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            RoomId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            Status = "Cancelled",
                            TotalPrice = 258.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
